/**
 * Test class for AddTopicToFeedItemHandler
 *
 * @editor Kelvin Ng
 * @version 2.4
 * @last edit 2018-9-11
 *
 * Add supplier, innovation
 *
 */

@isTest(SeeAllData=true)
private class AddTopicToFeedItemTriggerTest {
    /* Test data was impossible to create since the features developed is based on actual organization data on Salesforce
     * thus (SeeAllData=true) is used in this exceptional case
     */
    //---Tests for positive cases---//
    @isTest static void testFeedItemWithBrandCustomer() {
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}