/*****************************************************
Controller for Editing Announcement Article

1. The reason of having this controller is to build an the inline visualforce page to render a CKEditor for the announcement editing
2. Onchange Action Section
3. Button Action Section
4. Picklist Security Section

******************************************************/
public without sharing class ArticleEditPageController {
}