/*****************************************************
Article Wrapper Class

Constructor
1. Construct Article Wrapper includesadditional attribute
    a. picture URL 
    b. associated chatter feeds
    c. article Id
    d. feedsize
    e. distribute Grade 
    f. default language
    
Function setGrade()
2. Construct Grade String to show on the article feeds and lists

******************************************************/

public without sharing class ArticleWrapper {
}