/*****************************************************
Controller for Article Detail

1. Check if the user is allowed to edit the article
2. Get a list of article Ids for Button "Next" and "Previous"
3. Get the thumbnail URL of the article
4. Get the desired translated version for user

******************************************************/
public without sharing class ArticleDetailsController {
}