/*****************************************************
Controller for ArticleListPage

1. Get a list of articles to be shown to the user using StandardSetController
2. Wrap up with ArticleWrapper class to show on visualforce
	a. get the thumbnail of each article
	b. get the number of comments of each article
3. Get the URL of article list page that the user navigate to
4. Get the URL of full article page that the user navigate to 

******************************************************/
public without sharing class ArticleListPageController {    
}