public with sharing class SurveyConfigurationController {
    
    public static final String SURVEY_ALL_MY_SURVEY_LIST_VIEW_ID = System.Label.LABS_SF_AllMySurveyListViewId;
    public static final String SURVEY_MY_ACTIVE_SURVEYS_LIST_VIEW_ID = System.Label.LABS_SF_MyActiveSurveysListViewId;
    public static final String SURVEY_MY_INACTIVE_SURVEYS_LIST_VIEW_ID = System.Label.LABS_SF_MyInactiveSurveysListViewId;
    public static final String SURVEY_All_SURVEYS_LIST_VIEW_ID = System.Label.All_Surveys_List_View_Id;

    public SurveyConfigurationController() {
        
    }
}