@isTest
private class TestClassMigratoin {

    static testMethod void myUnitTest() {
        ArticleController extn1 = new ArticleController();
        ArticleDetailsController extn2 = new ArticleDetailsController();
        ArticleEditPageController extn3 = new ArticleEditPageController();
        ArticleListController extn4 = new ArticleListController();
        ArticleListPageController extn5 = new ArticleListPageController();
        ArticleWrapper extn6 = new ArticleWrapper();
        Portal_ContentTriggerHandler extn7 = new Portal_ContentTriggerHandler();
        PreviewPageController extn8 = new PreviewPageController();
        WebPortalAdminController extn9 = new WebPortalAdminController();
        WebPortalController extn10 = new WebPortalController();
        WebPortalMainPageController extn11 = new WebPortalMainPageController();
        
    }
}