@isTest
private class TestArticleWrapperClass {
	/*
    static testMethod void myUnitTest() {
        Portal_Content__c announcement = TestUtil.getAnnouncement();      	        
	    insert announcement;
	    
	    Map<Id, String> mapId2PicUrl = new Map<Id, String>();
	    mapId2PicUrl.put(announcement.Id, '/test.png');
	    ArticleWrapper ann1 = new ArticleWrapper(announcement, mapId2PicUrl);
	    
	    Integer i=0;
	    Map<Id, List<FeedItem>> mapFeedItems = new Map<Id, List<FeedItem>>();
	    announcement.Distribution_Grade__c='7;8;9;11;12;13;16;17;19;20';
	    ArticleWrapper ann2 = new ArticleWrapper(announcement, i, mapFeedItems, mapId2PicUrl);
	    system.assertEquals('Grades: 7 to 9, 11 to 13, 16 to 17, 19 to 20', ann2.distributeGrade);
	    
	    Portal_Content__c announcement2 = TestUtil.getAnnouncement();
	    announcement2.Tech_Id__c = announcement.Id;
	    announcement2.Distribution_Grade__c='21';
	    ArticleWrapper ann3 = new ArticleWrapper(announcement2, i, mapFeedItems, mapId2PicUrl);
	    system.assertEquals('Grade: 21', ann3.distributeGrade);
    }
    */
}