/*****************************************************
Controller for Setting Up a Page

1. Get all the setting records using the Unique Page name
2. Get Site Navigation Information
3. Get the components in the setting records
4. Insert Blank HTML component to those incorrectly set component block to avoid error
******************************************************/
public without sharing class WebPortalController {
    
}