/*****************************************************
Controller for Landing Tab (ConnecTAL) Page

Function getPageURL()
1. Find URL the default landing local site for the user
	Get    a. User Local Site
		   b. Specific Local Site Page Using the Unique Page Name
		   c. Specific Local Site template Name
		   d. Construct the landing Page URL
Function getDepartmentalPage()
2. Find URL of the departmental page
	Get    a. User Local Site and Department Name
		   b. Specific Local Site Page Using the Unique Page Name
		   c. Specific Local Site template Name
		   d. Construct the landing Page URL
******************************************************/
public without sharing class WebPortalMainPageController {

}