/*****************************************************
Controller for Portal Pages Administration

1. Edit Contents for Existing Page
    Select a. Distribution Category
           b. Distribution Site
           c. Department (Optional)
           d. Page Name
2. Create new Page
    Select a. Template Name
           b. Distribution Category
           c. Distribution Site
           d. Department (Optional)
           e. Page Name (Hidden - Default 'MainPage')
******************************************************/


public without sharing class WebPortalAdminController {
 
}